import { Router, type Request, type Response } from 'express';
import multer from 'multer';
import smilConverter from 'bodymovin-to-smil';
import { commonResponseHeaders } from '../middleware/security.js';
import { MAX_UPLOAD_SIZE_BYTES } from '../config.js';
import { fetchJsonWithLimits, validateHttpUrl } from '../utils/fetch-json.js';

const upload = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: MAX_UPLOAD_SIZE_BYTES },
  fileFilter: (_req, file, cb) => {
    // allow JSON mime types; reject others
    const ok =
      file.mimetype === 'application/json' ||
      file.mimetype === 'text/json' ||
      file.mimetype === 'application/octet-stream'; // sometimes JSON is sent as octet-stream
    if (ok) {
      cb(null, true);
    } else {
      cb(new Error('Only JSON files are allowed'));
    }
  },
});

export const convertRouter = Router();
convertRouter.use(commonResponseHeaders);

/**
 * POST /api/convert
 *
 * Accepts a Lottie/Bodymovin JSON via one of the following:
 * - multipart/form-data with field "file" containing a JSON file
 * - application/json or application/x-www-form-urlencoded with a "json" string field
 * - application/json or urlencoded with a "url" string field (http/https), which will be fetched
 *
 * Responds with an SVG (image/svg+xml) generated by bodymovin-to-smil.
 */
convertRouter.post(
  '/api/convert',
  upload.single('file'),
  async (req: Request, res: Response): Promise<void> => {
    try {
      let jsonData: unknown;

      if (req.file) {
        // Uploaded JSON file
        const text = req.file.buffer.toString('utf8');
        try {
          jsonData = JSON.parse(text) as unknown;
        } catch {
          res.status(400).json({ error: 'Uploaded file is not valid JSON' });
          return;
        }
      } else if (typeof req.body?.json === 'string') {
        try {
          jsonData = JSON.parse(req.body.json) as unknown;
        } catch {
          res.status(400).json({ error: 'Request field "json" is not valid JSON' });
          return;
        }
      } else if (typeof req.body?.url === 'string') {
        const url = validateHttpUrl(req.body.url);
        jsonData = await fetchJsonWithLimits(url);
      } else {
        res.status(400).json({ error: 'No file, json, or url provided' });
        return;
      }

      const svg = await smilConverter(jsonData);

      res.setHeader('Content-Type', 'image/svg+xml; charset=utf-8');
      res.status(200).send(svg);
    } catch (err) {
      // Normalize error
      const e = err as unknown as { message?: string; status?: number };
      const status = typeof e?.status === 'number' ? e.status : 500;
      const message = e?.message ?? 'Internal server error';
      if (status >= 500) {
        // Log only server-side issues
        // eslint-disable-next-line no-console
        console.error(err);
      }
      res.status(status).json({ error: message });
    }
  },
);

export default convertRouter;
